-- Parties (build plan 1.5). Additive: no column is dropped, narrowed, or
-- renamed, and every new column is nullable or carries a default, so this
-- applies to a database that already holds seeded Party rows.
--
-- The new Party columns are the ones an Ontario driver's licence yields that an
-- OREA form or a FINTRAC check consumes. The licence number and its expiry are
-- not among them — those belong to IdentityRecord, which Phase 2.5 writes.
--
-- `updatedAt` is generated by Prisma as NOT NULL with no default, which cannot
-- apply to a table with existing rows. The DEFAULT below is added by hand to
-- backfill them. Prisma sets this column on every write itself and does not
-- read the database-side default, so the two do not disagree.

-- AlterTable
ALTER TABLE "Party" ADD COLUMN     "address" TEXT,
ADD COLUMN     "city" TEXT,
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "dateOfBirth" DATE,
ADD COLUMN     "postalCode" TEXT,
ADD COLUMN     "province" TEXT,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
-- `deletedAt` is the soft delete, and it lives here rather than on Party: a
-- party removed from one transaction is untouched on every other one.
ALTER TABLE "TransactionParty" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "deletedAt" TIMESTAMP(3);
